# Generated by Django 6.0.6 on 2026-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('Nonrealise', 'Non réalisé'), ('Encours', 'En cours'), ('Realise', 'Réalisé')], default='Non réalisé', max_length=255)),
            ],
        ),
    ]
