# Generated by Django 6.0.6 on 2026-07-23 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AddField(
            model_name='action',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'action"),
        ),
        migrations.AlterField(
            model_name='action',
            name='statut',
            field=models.CharField(choices=[('NON_REALISE', 'Non réalisé'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé')], default='NON_REALISE', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'activité")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('NON_REALISE', 'Non réalisé'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé')], default='NON_REALISE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Action.action', verbose_name='Action parente')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la tâche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('NON_REALISE', 'Non réalisé'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé')], default='NON_REALISE', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Action.activite', verbose_name='Activité parente')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_creation'],
            },
        ),
    ]
